# Tested on Ubuntu 18.04.4 LTS
# deleted python-graphviz==0.8.4 from pip part
name: autogluon
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1g
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
    - alembic==1.4.2
    - autogluon==0.0.6
    - bcrypt==3.1.7
    - boto3==1.13.1
    - botocore==1.16.1
    - catboost==0.23
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.4.1
    - configparser==5.0.0
    - configspace==0.4.10
    - cryptography==2.9.2
    - cycler==0.10.0
    - cython==0.29.17
    - dask==2.6.0
    - databricks-cli==0.10.0
    - distributed==2.6.0
    - docker==4.2.0
    - docutils==0.15.2
    - flask==1.1.2
    - gitdb==4.0.4
    - gitpython==3.1.1
    - gluoncv==0.7.0
    - gluonnlp==0.8.1
    - gorilla==0.3.0
    - gunicorn==20.0.4
    - heapdict==1.0.1
    - idna==2.9
    - itsdangerous==1.1.0
    - jmespath==0.9.5
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - lightgbm==2.3.1
    - mako==1.1.2
    - matplotlib==3.2.1
    - mlflow==1.8.0
    - more-itertools==8.2.0
    - msgpack==1.0.0
    - mxnet==1.6.0
    - numpy==1.18.4
    - packaging==20.3
    - pandas==0.25.3
    - paramiko==2.7.1
    - pillow==6.2.1
    - plotly==4.6.0
    - pluggy==0.13.1
    - portalocker==1.7.0
    - prometheus-flask-exporter==0.13.0
    - protobuf==3.11.3
    - psutil==5.7.0
    - py==1.8.1
    - pyaml==20.4.0
    - pycparser==2.20
    - pynacl==1.3.0
    - pyparsing==2.4.7
    - pytest==5.4.1
    - python-editor==1.0.4
    - pytz==2020.1
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - requests==2.23.0
    - retrying==1.3.3
    - s3transfer==0.3.3
    - scikit-learn==0.22.2.post1
    - scikit-optimize==0.7.4
    - scipy==1.4.1
    - simplejson==3.17.0
    - smmap==3.0.2
    - sortedcontainers==2.1.0
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - tabulate==0.8.7
    - tblib==1.6.0
    - toolz==0.10.0
    - tqdm==4.46.0
    - typing==3.7.4.1
    - urllib3==1.25.9
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - zict==2.0.0