# Tested on Windows 10 version 1909 (OS Build 18363.778)
name: water
channels:
  - h2oai
  - anaconda
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - colorama=0.4.3
  - cryptography=2.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - future=0.18.2
  - h2o=3.28.1.2
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - libpng=1.6.37
  - libsodium=1.0.16
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - requests=2.23.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tabulate=0.8.3
  - terminado=0.8.3
  - testpath=0.4.4
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
    - alembic==1.4.2
    - click==7.1.2
    - cloudpickle==1.4.1
    - configparser==5.0.0
    - databricks-cli==0.10.0
    - docker==4.2.0
    - flask==1.1.2
    - gitdb==4.0.4
    - gitpython==3.1.1
    - gorilla==0.3.0
    - itsdangerous==1.1.0
    - mako==1.1.2
    - mlflow==1.8.0
    - prometheus-flask-exporter==0.13.0
    - protobuf==3.11.3
    - pypiwin32==223
    - python-editor==1.0.4
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - simplejson==3.17.0
    - smmap==3.0.2
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - waitress==1.4.3
    - websocket-client==0.57.0
    - werkzeug==1.0.1